# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test Flow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install dependencies
        run: npm install

      - name: Start app
        run: npm start > /dev/null 2>&1 &

      - name: Wait for app to start
        run: |
          echo "Waiting for app to start..."
          npx wait-on http://localhost:4200

      - name: Run Cypress tests
        run: npx cypress run --config baseUrl=http://localhost:4200

      - name: Stop app
        run: npm stop

      - name: Build
        if: success()
        run: npm run build

