name: Test Flow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install dependencies
        run: npm install

      - name: Start app
        run: npm start > /dev/null 2>&1 &

      - name: Wait for app to start
        run: |
          echo "Waiting for app to start..."
          npx wait-on http://localhost:4200

      - name: Run Cypress tests
        run: npx cypress run --config baseUrl=http://localhost:4200

      - name: Build
        if: success()
        run: npm run build

      - name: Upload video artifact
        if: always() # Upload the video artifact regardless of previous steps' success/failure
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: /

  download:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download video artifact
        uses: actions/download-artifact@v2
        with:
          name: cypress-videos

      - name: Move videos to public directory
        run: mv /
